name: Build and deploy 

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install 🔧
        run: yarn install
        working-directory: ./../

      - name: Build 🏗️
        run: |
          ls
        working-directory: ./../


      - name: Deploy to GH Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: apps/web/dist
