name: Build and Deploy

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the workflow on

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Change this to your Node.js version

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy to gh-pages
        run: |
          git config --global user.email "thor.demeestere@telenet.be"
          git config --global user.name "ThorD125"
          git checkout --orphan gh-pages
          git --work-tree apps/web/dist add --all
          git --work-tree apps/web/dist commit -m "Deploy to gh-pages"
          git push origin HEAD:gh-pages --force
